Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2020
Var
   n1, n2: inteiro
   m: real


Inicio
      Escreva ("Diga um número ")
      Leia (n1)
      Escreva ("Diga outro número ")
      Leia (n2)
      m <- (n1+n2)/2
      Escreva ("A média entre " ,n1," e ", n2, " é ", m)


Fimalgoritmo