Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2020
Var
n1, n2, s:inteiro


Inicio
      Escreva ("Escreva um número ")
      Leia (n1)
      Escreva ("Escreva outro número ")
      Leia (n2)
      s <- n1+n2
      Escreva ("A soma entre ", n1, " e ", n2, " é igual a ", s)


Fimalgoritmo