Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2020
Var
   angulo, s: real


Inicio
      Escreva ("Diga um ângulo ")
      Leia (angulo)
      s <- sen(GraupRad(angulo))
      Escreva ("O seno de " ,angulo, " é igual a " ,s)


Fimalgoritmo